Repository OCA/edi-framework, pull requests merged in 2023-10, with the labels that each got.

#17 [14.0] edi_state: do not break when no origin set
  edi_state_oca/models/edi_state_consumer_mixin.py
  edi_state_oca/tests/test_edi_state.py
Labels: bot is merging ⏳

#23 [16.0] edi: fix consumer get_view w/ nested forms
  edi_oca/models/edi_exchange_consumer_mixin.py
Labels: bot is merging ⏳

#18 [16.0][MIG] edi_record_metadata_oca: Migration to 16.0
  edi_record_metadata_oca/README.rst
  edi_record_metadata_oca/__init__.py
  edi_record_metadata_oca/__manifest__.py
  edi_record_metadata_oca/fields.py
  edi_record_metadata_oca/i18n/edi_record_metadata_oca.pot
  edi_record_metadata_oca/models/__init__.py
  edi_record_metadata_oca/models/edi_exchange_consumer_mixin.py
  edi_record_metadata_oca/models/edi_exchange_record.py
  edi_record_metadata_oca/readme/CONTRIBUTORS.rst
  edi_record_metadata_oca/readme/CREDITS.rst
  edi_record_metadata_oca/readme/DESCRIPTION.rst
  edi_record_metadata_oca/readme/USAGE.rst
  edi_record_metadata_oca/static/description/icon.png
  edi_record_metadata_oca/static/description/index.html
  edi_record_metadata_oca/tests/__init__.py
  edi_record_metadata_oca/tests/fake_models.py
  edi_record_metadata_oca/tests/test_metadata.py
  edi_record_metadata_oca/views/edi_exchange_record.xml
  setup/edi_record_metadata_oca/odoo/addons/edi_record_metadata_oca
  setup/edi_record_metadata_oca/setup.py
Labels: bot is merging ⏳

#22 [16.0][MIG] edi_state_oca: Migration to 16.0
  edi_state_oca/README.rst
  edi_state_oca/__init__.py
  edi_state_oca/__manifest__.py
  edi_state_oca/i18n/edi_state_oca.pot
  edi_state_oca/models/__init__.py
  edi_state_oca/models/edi_exchange_type.py
  edi_state_oca/models/edi_state.py
  edi_state_oca/models/edi_state_consumer_mixin.py
  edi_state_oca/models/edi_state_workflow.py
  edi_state_oca/readme/CONFIGURE.rst
  edi_state_oca/readme/CONTRIBUTORS.rst
  edi_state_oca/readme/CREDITS.rst
  edi_state_oca/readme/DESCRIPTION.rst
  edi_state_oca/readme/ROADMAP.rst
  edi_state_oca/readme/USAGE.rst
  edi_state_oca/security/ir_model_access.xml
  edi_state_oca/static/description/icon.png
  edi_state_oca/static/description/index.html
  edi_state_oca/tests/__init__.py
  edi_state_oca/tests/fake_models.py
  edi_state_oca/tests/test_edi_state.py
  edi_state_oca/views/edi_exchange_type.xml
  edi_state_oca/views/edi_state.xml
  edi_state_oca/views/edi_state_workflow.xml
  edi_state_oca/views/menuitems.xml
  setup/edi_state_oca/odoo/addons/edi_state_oca
  setup/edi_state_oca/setup.py
Labels: bot is merging ⏳

#15 [16.0][MIG] edi_account_oca
  edi_account_oca/README.rst
  edi_account_oca/__init__.py
  edi_account_oca/__manifest__.py
  edi_account_oca/i18n/edi_account.pot
  edi_account_oca/i18n/edi_account_oca.pot
  edi_account_oca/i18n/fr.po
  edi_account_oca/models/__init__.py
  edi_account_oca/models/account_move.py
  edi_account_oca/readme/CONTRIBUTORS.rst
  edi_account_oca/readme/DESCRIPTION.rst
  edi_account_oca/static/description/icon.png
  edi_account_oca/static/description/index.html
  edi_account_oca/tests/__init__.py
  edi_account_oca/tests/test_edi.py
  edi_account_oca/views/account_journal.xml
  edi_account_oca/views/account_move.xml
  edi_account_oca/views/edi_exchange_record.xml
  edi_account_oca/views/res_partner.xml
  setup/edi_account_oca/odoo/addons/edi_account_oca
  setup/edi_account_oca/setup.py
Labels: bot is merging ⏳

#20 [16.0][MIG] edi_party_data_oca: Migration to 16.0
  edi_party_data_oca/README.rst
  edi_party_data_oca/__init__.py
  edi_party_data_oca/__manifest__.py
  edi_party_data_oca/components/__init__.py
  edi_party_data_oca/components/common.py
  edi_party_data_oca/components/party_data.py
  edi_party_data_oca/i18n/edi_party_data_oca.pot
  edi_party_data_oca/models/__init__.py
  edi_party_data_oca/models/edi_exchange_type.py
  edi_party_data_oca/readme/CONFIGURE.rst
  edi_party_data_oca/readme/CONTRIBUTORS.rst
  edi_party_data_oca/readme/DESCRIPTION.rst
  edi_party_data_oca/readme/USAGE.rst
  edi_party_data_oca/static/description/icon.png
  edi_party_data_oca/static/description/index.html
  edi_party_data_oca/tests/__init__.py
  edi_party_data_oca/tests/test_party_data.py
  edi_party_data_oca/utils.py
  edi_party_data_oca/views/edi_exchange_type_views.xml
  setup/edi_party_data_oca/odoo/addons/edi_party_data_oca
  setup/edi_party_data_oca/setup.py
Labels: bot is merging ⏳

#28 [16.0] [MIG] edi_exchange_template_oca: Migration to 16.0
  edi_exchange_template_oca/README.rst
  edi_exchange_template_oca/__init__.py
  edi_exchange_template_oca/__manifest__.py
  edi_exchange_template_oca/components/__init__.py
  edi_exchange_template_oca/components/common.py
  edi_exchange_template_oca/components/output_mixin.py
  edi_exchange_template_oca/i18n/edi_exchange_template.pot
  edi_exchange_template_oca/i18n/edi_exchange_template_oca.pot
  edi_exchange_template_oca/models/__init__.py
  edi_exchange_template_oca/models/edi_backend.py
  edi_exchange_template_oca/models/edi_exchange_template_mixin.py
  edi_exchange_template_oca/models/edi_exchange_template_output.py
  edi_exchange_template_oca/readme/CONTRIBUTORS.rst
  edi_exchange_template_oca/readme/DESCRIPTION.rst
  edi_exchange_template_oca/security/ir_model_access.xml
  edi_exchange_template_oca/static/description/icon.png
  edi_exchange_template_oca/static/description/index.html
  edi_exchange_template_oca/tests/__init__.py
  edi_exchange_template_oca/tests/test_edi_backend_output.py
  edi_exchange_template_oca/utils.py
  edi_exchange_template_oca/views/edi_exchange_template_output_views.xml
  setup/edi_exchange_template_oca/odoo/addons/edi_exchange_template_oca
  setup/edi_exchange_template_oca/setup.py
Labels: approved, bot is merging ⏳

#19 [16.0][ADD] edi_edifact_oca
  edi_edifact_oca/README.rst
  edi_edifact_oca/__init__.py
  edi_edifact_oca/__manifest__.py
  edi_edifact_oca/components/__init__.py
  edi_edifact_oca/components/party_data.py
  edi_edifact_oca/data/edi_backend_type.xml
  edi_edifact_oca/demo/edi_backend_demo.xml
  edi_edifact_oca/readme/CONTRIBUTORS.rst
  edi_edifact_oca/readme/DESCRIPTION.rst
  edi_edifact_oca/static/description/icon.png
  edi_edifact_oca/static/description/index.html
  edi_edifact_oca/tests/__init__.py
  edi_edifact_oca/tests/test_party_data.py
  setup/edi_edifact_oca/odoo/addons/edi_edifact_oca
  setup/edi_edifact_oca/setup.py
Labels: approved, bot is merging ⏳

#34 [16.0][IMP] edi_oca: add company_id field with multi-company rule
  edi_oca/models/edi_exchange_record.py
  edi_oca/security/ir_model_access.xml
  edi_oca/views/edi_exchange_record_views.xml
Labels: bot is merging ⏳

#36 [14.0] dotfiles update needs manual intervention
  .copier-answers.yml
  .eslintrc.yml
  .github/workflows/pre-commit.yml
  .github/workflows/test.yml
  .pre-commit-config.yaml
  edi_state_oca/i18n/edi_state_oca.pot
  edi_state_oca/views/edi_state.xml
  edi_state_oca/views/edi_state_workflow.xml
Labels: help wanted, needs review, bot is merging ⏳
