Repository OCA/edi-framework, pull requests merged in 2024-05, with the labels that each got.

#81 [16.0] edi_storage: handle missing trailing slash
  edi_storage_oca/models/edi_backend.py
Labels: approved, ready to merge, bot is merging ⏳

#85 [16.0][FIX] edi_exchange_template_oca: Change SavepointCase to TransactionCase
  edi_exchange_template_oca/tests/test_nswrapper.py
Labels: approved, bot is merging ⏳

#84 [16.0][IMP] edi_oca: allow to receive empty files
  edi_oca/models/edi_backend.py
  edi_oca/models/edi_exchange_type.py
  edi_oca/tests/test_backend_input.py
  edi_oca/tests/test_backend_process.py
  edi_oca/views/edi_exchange_type_views.xml
Labels: approved, ready to merge
