Repository OCA/edi-framework, pull requests merged in 2024-07, with the labels that each got.

#90 [16.0][IMP] edi_oca: Don't run quick_exec if backend is not active
  edi_oca/models/edi_exchange_record.py
Labels: approved, ready to merge, bot is merging ⏳

#86 [16.0][IMP] edi_oca: add button to regenerate file after error on validation
  edi_oca/models/edi_backend.py
  edi_oca/models/edi_exchange_record.py
  edi_oca/tests/test_backend_validate.py
  edi_oca/views/edi_exchange_record_views.xml
Labels: approved, ready to merge, bot is merging ⏳

#94 [16.0][ADD] edi_exchange_deduplicate_oca
  edi_exchange_deduplicate_oca/README.rst
  edi_exchange_deduplicate_oca/__init__.py
  edi_exchange_deduplicate_oca/__manifest__.py
  edi_exchange_deduplicate_oca/data/cron.xml
  edi_exchange_deduplicate_oca/models/__init__.py
  edi_exchange_deduplicate_oca/models/edi_backend.py
  edi_exchange_deduplicate_oca/models/edi_exchange_record.py
  edi_exchange_deduplicate_oca/models/edi_exchange_type.py
  edi_exchange_deduplicate_oca/readme/CONFIGURE.rst
  edi_exchange_deduplicate_oca/readme/CONTRIBUTORS.rst
  edi_exchange_deduplicate_oca/readme/DESCRIPTION.rst
  edi_exchange_deduplicate_oca/readme/USAGE.rst
  edi_exchange_deduplicate_oca/static/description/index.html
  edi_exchange_deduplicate_oca/tests/__init__.py
  edi_exchange_deduplicate_oca/tests/test_edi_backend_cron.py
  edi_exchange_deduplicate_oca/tests/test_edi_duplicate.py
  edi_exchange_deduplicate_oca/views/edi_exchange_type_views.xml
  edi_oca/models/edi_backend.py
  setup/edi_exchange_deduplicate_oca/odoo/addons/edi_exchange_deduplicate_oca
  setup/edi_exchange_deduplicate_oca/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#96 [16.0][FWP] edi_oca: Fix Access error for Administrator (forward port)
  edi_oca/models/edi_exchange_record.py
  edi_oca/tests/test_security.py
Labels: bot is merging ⏳

#78 [16.0][ADD] edi_notification_oca
  edi_notification_oca/README.rst
  edi_notification_oca/__init__.py
  edi_notification_oca/__manifest__.py
  edi_notification_oca/components/__init__.py
  edi_notification_oca/components/listener.py
  edi_notification_oca/data/mail_activity_data.xml
  edi_notification_oca/models/__init__.py
  edi_notification_oca/models/edi_exchange_record.py
  edi_notification_oca/models/edi_exchange_type.py
  edi_notification_oca/readme/CONTRIBUTORS.rst
  edi_notification_oca/readme/CREDITS.rst
  edi_notification_oca/readme/DESCRIPTION.rst
  edi_notification_oca/static/description/icon.png
  edi_notification_oca/static/description/index.html
  edi_notification_oca/tests/__init__.py
  edi_notification_oca/tests/test_edi_notification.py
  edi_notification_oca/views/edi_exchange_type_views.xml
  setup/edi_notification_oca/odoo/addons/edi_notification_oca
  setup/edi_notification_oca/setup.py
Labels: bot is merging ⏳

#91 [17.0][MIG] edi_account_oca: Migration to 17.0
  edi_account_oca/README.rst
  edi_account_oca/__init__.py
  edi_account_oca/__manifest__.py
  edi_account_oca/i18n/edi_account.pot
  edi_account_oca/i18n/edi_account_oca.pot
  edi_account_oca/i18n/fr.po
  edi_account_oca/i18n/it.po
  edi_account_oca/models/__init__.py
  edi_account_oca/models/account_move.py
  edi_account_oca/pyproject.toml
  edi_account_oca/readme/CONTRIBUTORS.md
  edi_account_oca/readme/DESCRIPTION.md
  edi_account_oca/static/description/icon.png
  edi_account_oca/static/description/index.html
  edi_account_oca/tests/__init__.py
  edi_account_oca/tests/test_edi.py
  edi_account_oca/views/account_journal.xml
  edi_account_oca/views/account_move.xml
  edi_account_oca/views/edi_exchange_record.xml
  edi_account_oca/views/res_partner.xml
Labels: approved, bot is merging ⏳

#100 [16.0][FWD] edi_endpoint: fix form view inheritance
  edi_endpoint_oca/views/edi_endpoint_views.xml
Labels: bot is merging ⏳

#97 [17.0][FW][IMP] edi_oca: add button to regenerate file after error on validation
  edi_oca/models/edi_backend.py
  edi_oca/models/edi_exchange_record.py
  edi_oca/tests/test_backend_validate.py
  edi_oca/views/edi_exchange_record_views.xml
Labels: approved, ready to merge, bot is merging ⏳

#60 [MIG][17.0] edi_exchange_template_oca: Migration to 17.0
  edi_exchange_template_oca/README.rst
  edi_exchange_template_oca/__init__.py
  edi_exchange_template_oca/__manifest__.py
  edi_exchange_template_oca/components/__init__.py
  edi_exchange_template_oca/components/common.py
  edi_exchange_template_oca/components/output_mixin.py
  edi_exchange_template_oca/i18n/edi_exchange_template.pot
  edi_exchange_template_oca/i18n/edi_exchange_template_oca.pot
  edi_exchange_template_oca/i18n/it.po
  edi_exchange_template_oca/models/__init__.py
  edi_exchange_template_oca/models/edi_backend.py
  edi_exchange_template_oca/models/edi_exchange_template_mixin.py
  edi_exchange_template_oca/models/edi_exchange_template_output.py
  edi_exchange_template_oca/pyproject.toml
  edi_exchange_template_oca/readme/CONTRIBUTORS.md
  edi_exchange_template_oca/readme/DESCRIPTION.md
  edi_exchange_template_oca/security/ir_model_access.xml
  edi_exchange_template_oca/static/description/icon.png
  edi_exchange_template_oca/static/description/index.html
  edi_exchange_template_oca/tests/__init__.py
  edi_exchange_template_oca/tests/test_edi_backend_output.py
  edi_exchange_template_oca/tests/test_nswrapper.py
  edi_exchange_template_oca/utils.py
  edi_exchange_template_oca/views/edi_exchange_template_output_views.xml
Labels: approved, bot is merging ⏳
