Repository OCA/edi-framework, pull requests merged in 2024-01, with the labels that each got.

#50 [16.0][IMP] edi_product_oca: Plug EDI framework to product.packaging
  edi_product_oca/README.rst
  edi_product_oca/__manifest__.py
  edi_product_oca/models/__init__.py
  edi_product_oca/models/product_packaging.py
  edi_product_oca/readme/CONTRIBUTORS.rst
  edi_product_oca/readme/DESCRIPTION.rst
  edi_product_oca/static/description/index.html
  edi_product_oca/views/product_packaging_views.xml
Labels: bot is merging ⏳

#54 [16.0][ADD] edi_product_multi_barcode_oca
  edi_product_multi_barcode_oca/README.rst
  edi_product_multi_barcode_oca/__init__.py
  edi_product_multi_barcode_oca/__manifest__.py
  edi_product_multi_barcode_oca/models/__init__.py
  edi_product_multi_barcode_oca/models/product_barcode.py
  edi_product_multi_barcode_oca/readme/CONTRIBUTORS.rst
  edi_product_multi_barcode_oca/readme/CREDITS.rst
  edi_product_multi_barcode_oca/readme/DESCRIPTION.rst
  edi_product_multi_barcode_oca/static/description/icon.png
  edi_product_multi_barcode_oca/static/description/index.html
  setup/edi_product_multi_barcode_oca/odoo/addons/edi_product_multi_barcode_oca
  setup/edi_product_multi_barcode_oca/setup.py
Labels: bot is merging ⏳

#52 [16.0][IMP] edi_oca: add partner form page
  edi_account_oca/views/res_partner.xml
  edi_oca/__manifest__.py
  edi_oca/views/res_partner.xml
  edi_sale_oca/__manifest__.py
  edi_stock_oca/views/res_partner.xml
Labels: approved, ready to merge, bot is merging ⏳

#55 [FIX] edi_oca: tests using FakeModelLoader should not be post_install
  edi_oca/tests/test_consumer_mixin.py
  edi_oca/tests/test_security.py
Labels: bot is merging ⏳

#49 [16.0][ADD] edi_partner_oca
  edi_partner_oca/README.rst
  edi_partner_oca/__init__.py
  edi_partner_oca/__manifest__.py
  edi_partner_oca/models/__init__.py
  edi_partner_oca/models/res_partner.py
  edi_partner_oca/readme/CONTRIBUTORS.rst
  edi_partner_oca/readme/CREDITS.rst
  edi_partner_oca/readme/DESCRIPTION.rst
  edi_partner_oca/static/description/icon.png
  edi_partner_oca/static/description/index.html
  edi_partner_oca/views/partner_views.xml
  setup/edi_partner_oca/odoo/addons/edi_partner_oca
  setup/edi_partner_oca/setup.py
Labels: approved, bot is merging ⏳

#51 [16.0][MIG] edi_ubl_oca: Migration to 16.0
  edi_ubl_oca/README.rst
  edi_ubl_oca/__init__.py
  edi_ubl_oca/__manifest__.py
  edi_ubl_oca/data/edi_backend_type.xml
  edi_ubl_oca/demo/edi_backend_demo.xml
  edi_ubl_oca/i18n/edi_ubl_oca.pot
  edi_ubl_oca/readme/CONTRIBUTORS.rst
  edi_ubl_oca/readme/CREDITS.rst
  edi_ubl_oca/readme/DESCRIPTION.rst
  edi_ubl_oca/static/description/icon.png
  edi_ubl_oca/static/description/index.html
  setup/edi_ubl_oca/odoo/addons/edi_ubl_oca
  setup/edi_ubl_oca/setup.py
Labels: bot is merging ⏳

#57 [IMP] edi_oca: Allow to use a sequence as part of exchange filename pattern
  edi_oca/models/edi_exchange_type.py
  edi_oca/tests/common.py
  edi_oca/tests/test_exchange_type.py
  edi_oca/views/edi_exchange_type_views.xml
Labels: bot is merging ⏳

#63 [16.0][PORT] edi_oca + edi_exchange_template_oca: fwd port changes from edi/14.0
  .oca/oca-port/blacklist/edi_exchange_template_oca.json
  .oca/oca-port/blacklist/edi_oca.json
  edi_exchange_template_oca/README.rst
  edi_exchange_template_oca/__manifest__.py
  edi_exchange_template_oca/components/common.py
  edi_exchange_template_oca/components/output_mixin.py
  edi_exchange_template_oca/models/edi_backend.py
  edi_exchange_template_oca/models/edi_exchange_template_mixin.py
  edi_exchange_template_oca/models/edi_exchange_template_output.py
  edi_exchange_template_oca/static/description/index.html
  edi_exchange_template_oca/tests/__init__.py
  edi_exchange_template_oca/tests/test_edi_backend_output.py
  edi_exchange_template_oca/tests/test_nswrapper.py
  edi_exchange_template_oca/utils.py
  edi_exchange_template_oca/views/edi_exchange_template_output_views.xml
  edi_oca/models/edi_backend.py
  edi_oca/models/edi_exchange_consumer_mixin.py
  edi_oca/models/edi_exchange_record.py
  edi_oca/models/edi_exchange_type.py
  edi_oca/models/edi_exchange_type_rule.py
  edi_oca/models/edi_id_mixin.py
  edi_oca/tests/common.py
  edi_oca/tests/test_backend_jobs.py
  edi_oca/tests/test_backend_output.py
  edi_oca/tests/test_backend_process.py
  edi_oca/tests/test_backend_validate.py
  edi_oca/tests/test_exchange_type.py
  edi_oca/tests/test_record.py
  edi_oca/utils.py
  edi_oca/views/edi_backend_views.xml
  edi_oca/views/edi_exchange_record_views.xml
  edi_oca/views/edi_exchange_type_views.xml
  edi_sale_edifact_oca/tests/test_order.py
  edi_sale_oca/tests/test_process.py
Labels: bot is merging ⏳

#26 [16.0][MIG] edi_storage_oca: Migration to 16.0
  edi_storage_oca/README.rst
  edi_storage_oca/__init__.py
  edi_storage_oca/__manifest__.py
  edi_storage_oca/components/__init__.py
  edi_storage_oca/components/base.py
  edi_storage_oca/components/check.py
  edi_storage_oca/components/listener.py
  edi_storage_oca/components/receive.py
  edi_storage_oca/components/send.py
  edi_storage_oca/data/cron.xml
  edi_storage_oca/data/job_channel_data.xml
  edi_storage_oca/data/queue_job_function_data.xml
  edi_storage_oca/demo/edi_backend_demo.xml
  edi_storage_oca/models/__init__.py
  edi_storage_oca/models/edi_backend.py
  edi_storage_oca/models/edi_exchange_type.py
  edi_storage_oca/readme/CONTRIBUTORS.rst
  edi_storage_oca/readme/CREDITS.rst
  edi_storage_oca/readme/DESCRIPTION.rst
  edi_storage_oca/readme/ROADMAP.rst
  edi_storage_oca/readme/USAGE.rst
  edi_storage_oca/security/ir_model_access.xml
  edi_storage_oca/static/description/icon.png
  edi_storage_oca/static/description/index.html
  edi_storage_oca/tests/__init__.py
  edi_storage_oca/tests/common.py
  edi_storage_oca/tests/test_component_match.py
  edi_storage_oca/tests/test_components_base.py
  edi_storage_oca/tests/test_edi_backend_storage.py
  edi_storage_oca/tests/test_edi_storage_listener.py
  edi_storage_oca/tests/test_exchange_type.py
  edi_storage_oca/views/edi_backend_views.xml
  setup/edi_storage_oca/odoo/addons/edi_storage_oca
  setup/edi_storage_oca/setup.py
Labels: bot is merging ⏳
