Repository OCA/edi-framework, pull requests merged in 2025-01, with the labels that each got.

#131 [16.0] edi_storage_oca: Add migration Script
  edi_storage_oca/migrations/16.0.1.0.0/post-migrate.py
  edi_storage_oca/migrations/16.0.1.0.0/pre-migrate.py
Labels: merged 🎉

#116 [18.0][MIG] edi_account_oca
  edi_account_oca/README.rst
  edi_account_oca/__init__.py
  edi_account_oca/__manifest__.py
  edi_account_oca/i18n/edi_account.pot
  edi_account_oca/i18n/edi_account_oca.pot
  edi_account_oca/i18n/fr.po
  edi_account_oca/i18n/it.po
  edi_account_oca/models/__init__.py
  edi_account_oca/models/account_move.py
  edi_account_oca/pyproject.toml
  edi_account_oca/readme/CONTRIBUTORS.md
  edi_account_oca/readme/DESCRIPTION.md
  edi_account_oca/static/description/icon.png
  edi_account_oca/static/description/index.html
  edi_account_oca/tests/__init__.py
  edi_account_oca/tests/test_edi.py
  edi_account_oca/views/account_journal.xml
  edi_account_oca/views/account_move.xml
  edi_account_oca/views/edi_exchange_record.xml
  edi_account_oca/views/res_partner.xml
Labels: approved, ready to merge, bot is merging ⏳

#114 [17.0] [MIG] edi_storage_oca: Migration to 17.0
  edi_storage_oca/README.rst
  edi_storage_oca/__init__.py
  edi_storage_oca/__manifest__.py
  edi_storage_oca/components/__init__.py
  edi_storage_oca/components/base.py
  edi_storage_oca/components/check.py
  edi_storage_oca/components/listener.py
  edi_storage_oca/components/receive.py
  edi_storage_oca/components/send.py
  edi_storage_oca/data/cron.xml
  edi_storage_oca/data/job_channel_data.xml
  edi_storage_oca/data/queue_job_function_data.xml
  edi_storage_oca/demo/edi_backend_demo.xml
  edi_storage_oca/i18n/edi_storage_oca.pot
  edi_storage_oca/i18n/it.po
  edi_storage_oca/migrations/16.0.1.0.2/post-migrate.py
  edi_storage_oca/models/__init__.py
  edi_storage_oca/models/edi_backend.py
  edi_storage_oca/models/edi_exchange_record.py
  edi_storage_oca/models/edi_exchange_type.py
  edi_storage_oca/pyproject.toml
  edi_storage_oca/readme/CONTRIBUTORS.md
  edi_storage_oca/readme/CREDITS.md
  edi_storage_oca/readme/DESCRIPTION.md
  edi_storage_oca/readme/ROADMAP.md
  edi_storage_oca/readme/USAGE.md
  edi_storage_oca/security/ir_model_access.xml
  edi_storage_oca/static/description/icon.png
  edi_storage_oca/static/description/index.html
  edi_storage_oca/tests/__init__.py
  edi_storage_oca/tests/common.py
  edi_storage_oca/tests/test_component_match.py
  edi_storage_oca/tests/test_components_base.py
  edi_storage_oca/tests/test_edi_backend_storage.py
  edi_storage_oca/tests/test_edi_storage_listener.py
  edi_storage_oca/tests/test_exchange_type.py
  edi_storage_oca/utils.py
  edi_storage_oca/views/edi_backend_views.xml
Labels: approved, ready to merge, bot is merging ⏳

#64 [16.0][FIX] edi_storage_oca: FS find_files returns relative paths instead of full paths
  edi_storage_oca/models/edi_backend.py
Labels: bot is merging ⏳
